services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile.servidor
    container_name: servidor
    ports:
      - 50051:50051

  cliente:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    container_name: cliente
    depends_on:
      - servidor